//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALWEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int IdDetalleFactura { get; set; }
        public string Item { get; set; }
        public Nullable<decimal> ValorItem { get; set; }
        public Nullable<int> CantidadItem { get; set; }
        public Nullable<decimal> ValorItems { get; set; }
        public Nullable<int> IdFactura { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
